library(knitr)
library(BioNAR)
library(synaptome.db)
library(ggplot2)
library(pander)
library(ggrepel)
library(randomcoloR)
library(RSQLite)
library(synaptome.db)
library(igraph)

fullGraph <- read.graph("PostsynapticNetwork/FullPSDDBNetwork.gml", format="gml")

consensusGraph <- read.graph("PostsynapticNetwork/ConsensusPSDDBNetwork.gml", format = "gml")
fullGraphClustered <- calcClustering(fullGraph, alg = "louvain")
clusteringSummary()